/**
 * ACHIRA COUTURE - Centralized & Scalable Products Database
 * 
 * Supports multi-slot image structures:
 * {
 *   front: "...",
 *   side: "...",
 *   zoom: "...",
 *   palazzo: "...",
 *   dupatta: "...",
 *   back: "..."
 * }
 */

const ACHIRA_PRODUCTS_DATA = [
    // ==========================================
    // --- STRAIGHT FIT COLLECTION (Ethnic Wear) ---
    // ==========================================
    {
        id: "straight-001",
        numericId: 301,
        sku: "ACH-STR-001",
        name: "Noor-e-Gulab Blush Powder Pink Silk Sharara Set with Pearl Tassels",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Raw Silk & Chanderi",
        color: "Blush Powder Pink",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 25,
        status: "Active",
        featured: true,
        availability: "New Arrival",
        occasion: "Festive, Wedding Reception & Day Glamour",
        image: "products/straight-fit/product-01/front.jpg",
        images: {
            front: "products/straight-fit/product-01/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Ethereal blush powder pink straight-cut raw silk kurta adorned with delicate floral resham and silver threadwork embroidery along the neckline, shimmering pearl droplet tassels along the bottom hem, paired with wide pleated matching sharara pants and an intricately embroidered scalloped border dupatta.",
        careInstructions: "Dry clean only to maintain delicate pearl tassel detailing and the pristine sheen of pure raw silk.",
        deliveryInfo: "Dispatched within 24-48 hours. Express delivery across India in 3-5 business days."
    },
    {
        id: "straight-002",
        numericId: 302,
        sku: "ACH-STR-002",
        name: "Nazneen Deep Wine Magenta Silk Kurti with Embellished V-Yoke & Wide Palazzo Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Raw Silk & Fluid Crepe",
        color: "Deep Magenta / Wine Plum",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 28,
        status: "Active",
        featured: true,
        availability: "Trending",
        occasion: "Evening Soirees, Sangeet & Celebrations",
        image: "products/straight-fit/product-02/front.jpg",
        images: {
            front: "products/straight-fit/product-02/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Striking jewel-toned deep magenta wine straight-fit raw silk kurti featuring an intricately hand-embroidered multi-color resham and zardozi V-neckline yoke, sleek three-quarter sleeves, high side slits, paired with voluminous coordinated wide-leg palazzo pants.",
        careInstructions: "Dry clean only to preserve raw silk texture and fine metallic yoke embroidery.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-003",
        numericId: 303,
        sku: "ACH-STR-003",
        name: "Zehra Olive Mehendi Green Silk Kurta with Diamond Medallion & Scalloped Dupatta Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Silk & Sheer Organza",
        color: "Olive Mehendi Green",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 22,
        status: "Active",
        featured: true,
        availability: "Best Seller",
        occasion: "Mehendi, Haldi & Festive Celebrations",
        image: "products/straight-fit/product-03/front.jpg",
        images: {
            front: "products/straight-fit/product-03/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Sophisticated olive green straight-cut silk kurti highlighted by a geometric silver gota diamond medallion on the bodice with artisanal silk tassels, ornate sleeve embroidery, paired with relaxed pleated dhoti-sharara bottoms and a flowing scalloped embroidered dupatta with corner tassels.",
        careInstructions: "Dry clean only to maintain delicate silk tassels and metallic thread embellishments.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-004",
        numericId: 304,
        sku: "ACH-STR-004",
        name: "Mumtaz Royal Moss Green Silk Kurti with Handcrafted Chakra Medallion & Sharara Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Handloom Raw Silk & Chanderi",
        color: "Royal Moss Green",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 20,
        status: "Active",
        featured: true,
        availability: "New Arrival",
        occasion: "Royal Weddings, Sangeet & Festive Galas",
        image: "products/straight-fit/product-04/front.jpg",
        images: {
            front: "products/straight-fit/product-04/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Magnificent moss green raw silk straight kurti crowned by a grand circular sun medallion (chakra motif) handcrafted in gold zari and magenta resham embroidery, accented with pearl droplet tassels on the hem, paired with a flared gathered sharara and a luxurious gold-embroidered border dupatta.",
        careInstructions: "Professional dry clean only.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-005",
        numericId: 305,
        sku: "ACH-STR-005",
        name: "Roshni Dusty Mauve Lavender Silk Kurti with Tiered Sharara & Printed Organza Dupatta Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Mulberry Silk & Printed Organza",
        color: "Dusty Mauve Lavender",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 24,
        status: "Active",
        featured: true,
        availability: "Trending",
        occasion: "Day Weddings, Sangeet & Intimate Receptions",
        image: "products/straight-fit/product-05/front.jpg",
        images: {
            front: "products/straight-fit/product-05/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Regal dusty mauve lavender straight-fit pure silk kurti highlighted by silver resham threadwork along the neckline and front button placket, matched with dramatic tiered layered sharara pants and an ethereal floral-printed sheer organza dupatta framed in woven gold zari borders.",
        careInstructions: "Dry clean only.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-006",
        numericId: 306,
        sku: "ACH-STR-006",
        name: "Rani Gulbahar Fuchsia Pink Embroidered Silk Sharara Set with Scalloped Dupatta",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Raw Silk & Chanderi",
        color: "Fuchsia Hot Pink",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 26,
        status: "Active",
        featured: true,
        availability: "New Arrival",
        occasion: "Weddings, Sangeet & Festive Celebrations",
        image: "products/straight-fit/product-06/front.jpg",
        images: {
            front: "products/straight-fit/product-06/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Vibrant and celebratory fuchsia pink straight-cut raw silk kurta decorated with silver resham embroidery along the split neckline, intricate booti motifs and geometric hem borders, paired with a matching voluminous tiered flared sharara and an embroidered scalloped dupatta.",
        careInstructions: "Dry clean only to maintain raw silk texture and fine silver resham embroidery.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-007",
        numericId: 307,
        sku: "ACH-STR-007",
        name: "Mehrunissa Deep Royal Purple Silk Kurta with Intricate Zardozi Work & Pants Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Mulberry Silk",
        color: "Royal Deep Purple",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 22,
        status: "Active",
        featured: true,
        availability: "Best Seller",
        occasion: "Evening Galas, Receptions & Festive Puja",
        image: "products/straight-fit/product-07/front.jpg",
        images: {
            front: "products/straight-fit/product-07/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Enchanting royal deep purple sleeveless straight-fit pure silk kurta highlighted by an ornate neckline laden with antique gold zardozi and delicate resham work, bordered hemline, paired with tailored straight cigarette pants and a sweeping all-over booti dupatta.",
        careInstructions: "Dry clean only.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-008",
        numericId: 308,
        sku: "ACH-STR-008",
        name: "Sitara Ivory & Aubergine Purple Contrast Embroidered Sharara Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Chanderi Silk & Pure Mulmul",
        color: "Ivory Cream / Aubergine Purple",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 20,
        status: "Active",
        featured: true,
        availability: "Trending",
        occasion: "Day Weddings, Sangeet & Intimate Receptions",
        image: "products/straight-fit/product-08/front.jpg",
        images: {
            front: "products/straight-fit/product-08/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Opulent two-tone contrast ensemble featuring an ivory cream straight-cut silk kurta adorned with rich aubergine purple floral embroidery on the bodice and cuffs, paired with a sweeping aubergine purple flared sharara and an ethereal matching sheer dupatta with gota borders.",
        careInstructions: "Dry clean only.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-009",
        numericId: 309,
        sku: "ACH-STR-009",
        name: "Kashvi Mustard Gold Silk Kurti with Jharokha Motif & Flared Sharara Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Silk & Sheer Organza",
        color: "Mustard Gold Yellow",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 25,
        status: "Active",
        featured: true,
        availability: "New Arrival",
        occasion: "Haldi, Mehendi & Morning Wedding Rituals",
        image: "products/straight-fit/product-09/front.jpg",
        images: {
            front: "products/straight-fit/product-09/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Luminous mustard gold straight-fit silk kurta styled with an elaborate V-neckline yoke, architectural temple jharokha floral motifs along the bottom border, bell sleeves, coordinated with gathered dhoti-sharara bottoms and an embroidered sheer organza dupatta.",
        careInstructions: "Dry clean only to maintain delicate silk sheen and handwork.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-010",
        numericId: 310,
        sku: "ACH-STR-010",
        name: "Aastha Ice Blue Silk Sharara Set with Silver Flora & Pearl Droplet Tassels",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Tissue Silk & Chanderi",
        color: "Ice Blue / Powder Blue",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 24,
        status: "Active",
        featured: true,
        availability: "Best Seller",
        occasion: "Receptions, Cocktails & Summer Soirees",
        image: "products/straight-fit/product-10/front.jpg",
        images: {
            front: "products/straight-fit/product-10/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Breathtaking ice powder blue tissue silk straight-cut kurti crowned with silver floral threadwork on the V-neckline and vertical panels, shimmering pearl droplet tassels along the bottom hem, paired with a wide flared metallic-sheen sharara skirt and an embroidered scalloped dupatta.",
        careInstructions: "Dry clean only to protect delicate pearl droplets and tissue silk weave.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-011",
        numericId: 311,
        sku: "ACH-STR-011",
        name: "Gulnaaz Tea-Rose Pink Sleeveless Silk Kurti with Printed Dupatta Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Mulberry Silk & Chanderi",
        color: "Tea-Rose Pink / Soft Blush",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 25,
        status: "Active",
        featured: true,
        availability: "New Arrival",
        occasion: "Summer Soirees, Day Festive & Intimate Gatherings",
        image: "products/straight-fit/product-11/front.jpg",
        images: {
            front: "products/straight-fit/product-11/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Graceful sleeveless tea-rose pink straight-cut raw silk kurti with an embellished V-neckline adorned with rose-gold and metallic resham embroidery, high side slits, paired with tonal wide-leg straight palazzo trousers and an artistic floral-printed pure silk dupatta.",
        careInstructions: "Dry clean only to maintain raw silk texture and delicate metallic resham embroidery.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-012",
        numericId: 312,
        sku: "ACH-STR-012",
        name: "Afreen Peach Coral Silk Kurti with Rani Embroidered Yoke & Sharara Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Tissue Silk & Chanderi",
        color: "Peach Coral / Rani Pink",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 22,
        status: "Active",
        featured: true,
        availability: "Trending",
        occasion: "Festive Celebrations, Mehendi & Weddings",
        image: "products/straight-fit/product-12/front.jpg",
        images: {
            front: "products/straight-fit/product-12/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Lustrous peach coral tissue silk straight kurti featuring an opulent rani-pink and gold zardozi embroidered sweetheart neck yoke, three-quarter sleeves, paired with a matching flared pleated sharara skirt and a dramatic striped golden zari rani pink dupatta.",
        careInstructions: "Dry clean only.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-013",
        numericId: 313,
        sku: "ACH-STR-013",
        name: "Heena Raspberry Fuchsia Silk Kurta Set with Chevron Needlework",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Silk & Chanderi",
        color: "Raspberry Fuchsia",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 26,
        status: "Active",
        featured: true,
        availability: "Best Seller",
        occasion: "Festive Gatherings, Puja & Sangeet",
        image: "products/straight-fit/product-13/front.jpg",
        images: {
            front: "products/straight-fit/product-13/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Refined raspberry fuchsia straight-cut silk kurti styled with a vertical chevron embroidered neckline placket, shimmering diamond grid booti on the hemline and sleeves, coordinated with tailored straight cigarette pants and a matching all-over booti dupatta.",
        careInstructions: "Dry clean only to maintain silk lustre and needlework precision.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-014",
        numericId: 314,
        sku: "ACH-STR-014",
        name: "Inaya Dusty Cocoa Taupe Kurti Set with Hand-Painted Floral Dupatta",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Chanderi & Sheer Organza",
        color: "Dusty Cocoa Mocha Taupe",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 20,
        status: "Active",
        featured: true,
        availability: "New Arrival",
        occasion: "Day Festive, Sangeet & Cocktail Soirees",
        image: "products/straight-fit/product-14/front.jpg",
        images: {
            front: "products/straight-fit/product-14/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Chic dusty cocoa mocha taupe kurti set featuring artisanal floral appliques on a striped yoke panel, pleated empire waist, straight relaxed trousers, paired with an organza dupatta decorated with hand-painted botanical rose motifs and lace scalloped borders.",
        careInstructions: "Professional dry clean only.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-015",
        numericId: 315,
        sku: "ACH-STR-015",
        name: "Tara Ivory & Lilac Silk Kurti with Fringe Tassels & Sharara Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Chanderi Silk & Mulmul",
        color: "Ivory Cream / Lilac Purple",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 24,
        status: "Active",
        featured: true,
        availability: "Trending",
        occasion: "Day Weddings, Haldi, Mehendi & Celebrations",
        image: "products/straight-fit/product-15/front.jpg",
        images: {
            front: "products/straight-fit/product-15/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Bohemian-luxe ivory straight silk kurta featuring delicate lavender floral embroidery on the split round neck and hem, whimsical cotton thread fringe tassels along hemline and sleeve cuffs, paired with a flared lilac sharara skirt with matching tassel borders and a coordinating lilac dupatta.",
        careInstructions: "Dry clean only to maintain delicate fringe tassel detailing.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-016",
        numericId: 316,
        sku: "ACH-STR-016",
        name: "Zunaira Chartreuse Lime Silk Sleeveless Sharara Set with Floral Borders",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Raw Silk & Chanderi",
        color: "Chartreuse Lime Green",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 25,
        status: "Active",
        featured: true,
        availability: "New Arrival",
        occasion: "Mehendi, Haldi, Sangeet & Festive Soirees",
        image: "products/straight-fit/product-16/front.jpg",
        images: {
            front: "products/straight-fit/product-16/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Luminous chartreuse lime green sleeveless straight-cut raw silk kurti featuring multi-colored floral resham embroidery on the scoop neckline and hemline, paired with a matching voluminous flared pleated sharara skirt with embroidered borders and a delicate booti dupatta.",
        careInstructions: "Dry clean only to maintain raw silk texture and fine resham embroidery.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-017",
        numericId: 317,
        sku: "ACH-STR-017",
        name: "Ruhi Terracotta Rust Silk Sharara Set with Beadwork Neckline",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Handloom Raw Silk & Organza",
        color: "Terracotta Rust / Copper Orange",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 22,
        status: "Active",
        featured: true,
        availability: "Trending",
        occasion: "Autumn Weddings, Day Festive & Celebrations",
        image: "products/straight-fit/product-17/front.jpg",
        images: {
            front: "products/straight-fit/product-17/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Earthy terracotta copper rust raw silk sleeveless straight kurti adorned with intricate zardozi and beadwork along the neckline, delicate floral embroidery along the bottom hem, paired with a matching tiered flared sharara bottom and an embroidered sheer organza dupatta.",
        careInstructions: "Dry clean only.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-018",
        numericId: 318,
        sku: "ACH-STR-018",
        name: "Meera Pistachio Lime Silk Kurta Set with Botanical Threadwork",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Chanderi Silk",
        color: "Pistachio Lime Green",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 26,
        status: "Active",
        featured: true,
        availability: "Best Seller",
        occasion: "Day Weddings, Festive Puja & Receptions",
        image: "products/straight-fit/product-18/front.jpg",
        images: {
            front: "products/straight-fit/product-18/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Exquisite pistachio lime green straight-fit silk kurta styled with an elaborate vertical front panel of intricate floral resham threadwork, split round neck, tailored straight trousers with embroidered cuffs, paired with a matching embroidered border dupatta.",
        careInstructions: "Dry clean only to maintain delicate threadwork and silk texture.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-019",
        numericId: 319,
        sku: "ACH-STR-019",
        name: "Ananya Marigold Yellow Jacquard Silk Kurta Set with Mirror Work",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Woven Jacquard Silk & Chanderi",
        color: "Marigold Golden Yellow",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 20,
        status: "Active",
        featured: true,
        availability: "New Arrival",
        occasion: "Haldi Ceremony, Festive Puja & Family Gatherings",
        image: "products/straight-fit/product-19/front.jpg",
        images: {
            front: "products/straight-fit/product-19/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Radiant marigold golden yellow self-woven jacquard straight kurti enriched with intricate geometric borders and subtle mirror-work on the neckline placket, paired with tailored straight-fit trousers and a lightweight matching golden dupatta.",
        careInstructions: "Professional dry clean only.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-020",
        numericId: 320,
        sku: "ACH-STR-020",
        name: "Alia Rose Quartz Powder Pink Sleeveless Brocade Kurti Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Brocade Silk & Flowy Chiffon",
        color: "Powder Pink / Rose Quartz",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 24,
        status: "Active",
        featured: true,
        availability: "Trending",
        occasion: "Summer Weddings, Receptions & Elegant Day Parties",
        image: "products/straight-fit/product-20/front.jpg",
        images: {
            front: "products/straight-fit/product-20/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Serene rose quartz powder pink sleeveless brocade straight kurti featuring an embellished V-neckline adorned with multi-color pastel embroidery, woven gold tissue hem border, paired with fluid wide palazzo trousers and an airy chiffon dupatta with golden tissue borders.",
        careInstructions: "Dry clean only to preserve brocade lustre and delicate embroidery.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-021",
        numericId: 321,
        sku: "ACH-STR-021",
        name: "Aaira Sea Green Raw Silk Kurta Set with Botanical Printed Dupatta",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Raw Silk & Chanderi",
        color: "Sea Green / Muted Teal",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 24,
        status: "Active",
        featured: true,
        availability: "New Arrival",
        occasion: "Festive Celebrations, Puja & Elegant Day Events",
        image: "products/straight-fit/product-21/front.jpg",
        images: {
            front: "products/straight-fit/product-21/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Lustrous sea green raw silk straight-cut kurti highlighted by an intricate hand-embroidered neckline yoke in metallic zardozi and multi-hue resham, three-quarter sleeves, tailored straight trousers, paired with a magnificent floral botanical printed sheer dupatta edged with rich woven gold zari borders.",
        careInstructions: "Dry clean only to maintain raw silk lustre and the delicate botanical print dupatta.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-022",
        numericId: 322,
        sku: "ACH-STR-022",
        name: "Ruhani Deep Plum Mauve Silk Kurti with Leheriya Striped Zari Dupatta Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Mulberry Silk & Chanderi",
        color: "Deep Plum Wine / Dusty Mauve",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 22,
        status: "Active",
        featured: true,
        availability: "Trending",
        occasion: "Evening Receptions, Sangeet & Intimate Soirees",
        image: "products/straight-fit/product-22/front.jpg",
        images: {
            front: "products/straight-fit/product-22/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Regal sleeveless deep plum mauve silk straight kurti featuring an opulent vertical neckline yoke intricately embroidered in antique gold and pastel resham needlework, paired with matching wide-leg trousers and a dramatic contrast candy pink and golden striped leheriya zari dupatta.",
        careInstructions: "Dry clean only to preserve fine hand embroidery and silk texture.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-023",
        numericId: 323,
        sku: "ACH-STR-023",
        name: "Mahira Ivory & Peach Floral Cape-Layered Silk Sharara Set with Fringe Tassels",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Chanderi Silk & Mulmul",
        color: "Ivory Cream / Peach Floral",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 20,
        status: "Active",
        featured: true,
        availability: "New Arrival",
        occasion: "Day Weddings, Haldi, Mehendi & Celebrations",
        image: "products/straight-fit/product-23/front.jpg",
        images: {
            front: "products/straight-fit/product-23/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Artisanal ivory cream straight-cut tunic detailed with delicate chikankari needlework on the yoke, statement cotton fringe droplet tassels along the hemline, an asymmetric botanical peach-printed cape drape, paired with a matching printed flared sharara skirt and tassel-trimmed dupatta.",
        careInstructions: "Dry clean only to protect delicate fringe tassel detailing and hand-block prints.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-024",
        numericId: 324,
        sku: "ACH-STR-024",
        name: "Sultana Ice Blue Raw Silk Kurti with Scalloped Embroidered Sharara Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Raw Silk & Chanderi",
        color: "Ice Blue / Powder Mint",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 25,
        status: "Active",
        featured: true,
        availability: "Best Seller",
        occasion: "Wedding Receptions, Sangeet & Festive Galas",
        image: "products/straight-fit/product-24/front.jpg",
        images: {
            front: "products/straight-fit/product-24/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Enchanting ice blue straight-cut raw silk kurti featuring delicate floral resham threadwork across the split neckline, intricate cutwork scalloped borders on sleeves and hem, paired with a voluminous flared matching sharara skirt with all-over embroidered buttis and an embroidered scalloped dupatta.",
        careInstructions: "Dry clean only to maintain scalloped cutwork and pure raw silk sheen.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-025",
        numericId: 325,
        sku: "ACH-STR-025",
        name: "Nayantara Terracotta Rust Raw Silk Sleeveless Kurta Palazzo Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Handloom Raw Silk",
        color: "Terracotta Rust / Brick Red",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 22,
        status: "Active",
        featured: true,
        availability: "Trending",
        occasion: "Festive Puja, Evening Receptions & Family Celebrations",
        image: "products/straight-fit/product-25/front.jpg",
        images: {
            front: "products/straight-fit/product-25/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Exquisite terracotta rust sleeveless raw silk straight kurta showcasing an ornate scalloped sweetheart neckline with golden zardozi needlework, delicate floral booti motifs throughout, matched with wide-leg palazzo pants with rich embroidered hem borders and a coordinated scalloped border dupatta.",
        careInstructions: "Dry clean only to protect delicate metallic zardozi embroidery.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-026",
        numericId: 326,
        sku: "ACH-STR-026",
        name: "Gauri Emerald Green Raw Silk Kurta Set with Rose Printed Dupatta",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Raw Silk & Sheer Organza",
        color: "Emerald Bottle Green",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 25,
        status: "Active",
        featured: true,
        availability: "New Arrival",
        occasion: "Weddings, Mehendi, Sangeet & Royal Festivities",
        image: "products/straight-fit/product-26/front.jpg",
        images: {
            front: "products/straight-fit/product-26/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Regal emerald green raw silk straight kurti adorned with an intricately hand-embroidered floral V-neckline yoke, shimmering micro-booti highlights, coordinated with matching flared palazzo bottoms and a dramatic blooming rose-printed organza dupatta framed with woven gold zari borders.",
        careInstructions: "Dry clean only to maintain pristine raw silk lustre and the delicate rose-printed dupatta.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-027",
        numericId: 327,
        sku: "ACH-STR-027",
        name: "Siya Crimson Tangerine Silk Kurti with Dual-Tone Leheriya Dupatta Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Chanderi Silk & Flowy Chiffon",
        color: "Crimson Tangerine / Purple",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 22,
        status: "Active",
        featured: true,
        availability: "Trending",
        occasion: "Festive Celebrations, Haldi & Day Weddings",
        image: "products/straight-fit/product-27/front.jpg",
        images: {
            front: "products/straight-fit/product-27/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Luminous crimson tangerine silk straight kurti featuring an elaborate purple and gold zardozi embroidered bodice yoke and ornate hem border, paired with relaxed wide-leg flared pants and a mesmerizing dual-tone magenta purple & tangerine leheriya striped dupatta with scalloped borders.",
        careInstructions: "Dry clean only to preserve intricate zari embroidery and hand-dyed leheriya dupatta.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-028",
        numericId: 328,
        sku: "ACH-STR-028",
        name: "Rhea Soft Rose Pink Silk Sharara Set with Scalloped Floral Needlework",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Mulberry Silk & Chanderi",
        color: "Rose Quartz / Candy Blush",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 24,
        status: "Active",
        featured: true,
        availability: "New Arrival",
        occasion: "Day Weddings, Engagement & Intimate Receptions",
        image: "products/straight-fit/product-28/front.jpg",
        images: {
            front: "products/straight-fit/product-28/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Ethereal candy blush pink straight-cut silk kurti styled with a rich multi-colored resham, bead and sequin embroidered sweetheart neckline yoke, scalloped floral hem border, matched with tiered flared sharara pants and an elegant tonal silk dupatta with golden lace edging.",
        careInstructions: "Dry clean only to preserve fine needlework and delicate sequin embellishments.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-029",
        numericId: 329,
        sku: "ACH-STR-029",
        name: "Avani Pastel Lilac Silk Kurta Set with Botanical Garden Embroidery",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Mulberry Silk & Chanderi",
        color: "Pastel Lilac / Soft Mauve",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 26,
        status: "Active",
        featured: true,
        availability: "Best Seller",
        occasion: "Day Festive, Summer Soirees & Family Gatherings",
        image: "products/straight-fit/product-29/front.jpg",
        images: {
            front: "products/straight-fit/product-29/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Charming pastel lilac straight silk kurta highlighting intricate tone-on-tone botanical threadwork embroidery along the V-neckline, scattering booti motifs, and an elaborate floral garden embroidered hemline, paired with tailored straight-fit trousers and an embroidered floral border dupatta.",
        careInstructions: "Dry clean only to maintain silk sheen and delicate botanical threadwork.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-030",
        numericId: 330,
        sku: "ACH-STR-030",
        name: "Vandana Ruby Fuchsia Pink Silk Kurta Set with Gold Zari Placket & Banarasi Dupatta",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Raw Silk & Woven Chanderi",
        color: "Ruby Fuchsia / Deep Rose Pink",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 20,
        status: "Active",
        featured: true,
        availability: "Trending",
        occasion: "Royal Weddings, Receptions & Grand Celebrations",
        image: "products/straight-fit/product-30/front.jpg",
        images: {
            front: "products/straight-fit/product-30/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Magnificent ruby fuchsia pink straight raw silk kurta crowned by a grand antique gold zardozi embroidered neckline placket and sleeve cuffs, paired with wide-leg relaxed palazzo pants and a regal gold-printed woven Banarasi chanderi dupatta finished with corner tassels.",
        careInstructions: "Professional dry clean only to maintain gold zari work and rich woven dupatta.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-031",
        numericId: 331,
        sku: "ACH-STR-031",
        name: "Kavya Aubergine Plum Silk Kurti with Bandhani Printed Sharara & Dupatta Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Silk & Fluid Georgette",
        color: "Deep Aubergine Plum / Wine",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 24,
        status: "Active",
        featured: true,
        availability: "New Arrival",
        occasion: "Festive Celebrations, Sangeet & Evening Soirees",
        image: "products/straight-fit/product-31/front.jpg",
        images: {
            front: "products/straight-fit/product-31/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Regal deep aubergine plum straight-cut silk kurti accented with a delicate floral resham star motif on the round neckline, embroidered booti work, paired with a matching flared skirt adorned with intricate traditional Bandhani micro-dot patterns and a coordinating all-over printed dupatta.",
        careInstructions: "Dry clean only to protect delicate silk texture and intricate bandhani print detailing.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-032",
        numericId: 332,
        sku: "ACH-STR-032",
        name: "Mira Blush Pink Cotton Silk Tunic Set with Cutwork Lace & Floral Embroidery",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Cotton Silk & Chanderi",
        color: "Blush Candy Pink",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 26,
        status: "Active",
        featured: true,
        availability: "Trending",
        occasion: "Day Soirees, Summer Brunches & Intimate Gatherings",
        image: "products/straight-fit/product-32/front.jpg",
        images: {
            front: "products/straight-fit/product-32/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Graceful blush candy pink straight tunic featuring ivory botanical vine thread embroidery on the hemline and trousers, pintuck pleated bell sleeves with scalloped cutwork lace trim, matching V-neckline border, paired with tailored straight-cut trousers with embroidered cuffs.",
        careInstructions: "Dry clean or gentle hand wash separately in cold water.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-033",
        numericId: 333,
        sku: "ACH-STR-033",
        name: "Tanvi Lavender Lilac Silk Kurti with Rani Pink Yoke & Striped Zari Dupatta Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Silk & Tissue Chanderi",
        color: "Lavender Lilac / Rani Pink",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 22,
        status: "Active",
        featured: true,
        availability: "Best Seller",
        occasion: "Mehendi, Sangeet & Festive Wedding Celebrations",
        image: "products/straight-fit/product-33/front.jpg",
        images: {
            front: "products/straight-fit/product-33/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Vibrant two-tone ensemble featuring a pastel lavender lilac straight silk kurti with a rich contrast rani hot pink V-neckline yoke laden with silver gota and thread embroidery, paired with a flared gathered sharara bottom and a dramatic diagonal gold zari striped rani pink dupatta.",
        careInstructions: "Dry clean only to maintain raw silk lustre and contrast needlework.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-034",
        numericId: 334,
        sku: "ACH-STR-034",
        name: "Rhea Rose Powder Pink Tissue Silk Kurta Set with Chevron Gota Patti",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Tissue Silk & Woven Brocade",
        color: "Powder Pink / Rose Blush",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 25,
        status: "Active",
        featured: true,
        availability: "New Arrival",
        occasion: "Summer Weddings, Day Festive & Engagement Parties",
        image: "products/straight-fit/product-34/front.jpg",
        images: {
            front: "products/straight-fit/product-34/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Luminous rose powder pink tissue silk straight-cut kurti adorned with diagonal chevron gota patti lines across the bodice framed in gold embroidery, woven brocade geometric hem borders, paired with a matching flared sharara skirt and a diaphanous tissue dupatta with gold lace borders.",
        careInstructions: "Dry clean only to preserve tissue silk weave and fine metallic gota work.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    },
    {
        id: "straight-035",
        numericId: 335,
        sku: "ACH-STR-035",
        name: "Devika Peacock Teal Embroidered Silk Jacket Gown with Belt & Dupatta Set",
        category: "Straight Fit",
        parentCategory: "Ethnic Wear",
        fabric: "Pure Silk Georgette & Organza",
        color: "Peacock Teal / Deep Ocean Green",
        size: ["S", "M", "L", "XL", "XXL"],
        price: null,
        originalPrice: null,
        discountPrice: null,
        stock: 20,
        status: "Active",
        featured: true,
        availability: "Trending",
        occasion: "Royal Galas, Receptions & Grand Festive Weddings",
        image: "products/straight-fit/product-35/front.jpg",
        images: {
            front: "products/straight-fit/product-35/front.jpg",
            side: "",
            zoom: "",
            palazzo: "",
            dupatta: "",
            back: ""
        },
        rating: 5,
        description: "Breathtaking deep peacock teal layered silk ensemble showcasing all-over intricate ivory floral threadwork embroidery, structured straight-fit front-open jacket silhouette with an embellished waist belt, coordinated tiered inner skirt, and a sheer embroidered border dupatta.",
        careInstructions: "Professional dry clean only.",
        deliveryInfo: "Dispatched within 24-48 hours across India."
    }
];

// Provide to Global Window Scope
if (typeof window !== 'undefined') {
    window.ACHIRA_PRODUCTS_DATA = ACHIRA_PRODUCTS_DATA;
}

// Support Node.js export if used in server environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { ACHIRA_PRODUCTS_DATA };
}
